FROM amazoncorretto:21-alpine-jdk AS builder
WORKDIR /app

COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY gradlew .
COPY gradle ./gradle

RUN ./gradlew dependencies --no-daemon || return 0

COPY src ./src
RUN ./gradlew clean build -x test --no-daemon --parallel

FROM amazoncorretto:21-alpine-jdk
WORKDIR /app
RUN apk add --no-cache curl openssl bash libc6-compat

COPY --from=builder /app/build/libs/mingxue-0.0.1-SNAPSHOT.jar backend.jar

RUN addgroup -S spring && adduser -S spring -G spring
USER spring

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "backend.jar"]
