FROM amazoncorretto:21-alpine-jdk AS builder
WORKDIR /app
COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY gradlew .
COPY gradle ./gradle
COPY src ./src
RUN ./gradlew clean build -x test

FROM amazoncorretto:21-alpine-jdk
WORKDIR /app

# Install required dependencies
RUN apk add --no-cache curl openssl bash libc6-compat

COPY --from=builder /app/build/libs/mingxue-0.0.1-SNAPSHOT.jar backend.jar

# Add a non-root user for security
RUN addgroup -S spring && adduser -S spring -G spring
RUN chown -R spring:spring /app
USER spring

# Expose the application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "backend.jar"]
