FROM golang:1.23-alpine AS build

RUN apk add --no-cache ffmpeg

ENV FFMPEG_PATH="/usr/bin/ffmpeg"

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o tts ./src

FROM alpine:latest

RUN apk --no-cache add ca-certificates ffmpeg

ENV FFMPEG_PATH="/usr/bin/ffmpeg"
ENV DOCKER_ENV="true"

WORKDIR /root/
COPY --from=build /app/tts . 

CMD ["./tts"]
